import { GeistSans } from "geist/font";
import "./globals.css";

export const metadata = {
  title: "Blog - willyw.dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={GeistSans.className}>
      <body className='mt-14 text-zinc-100 bg-zinc-950'>{children}</body>
    </html>
  );
}
